name = "gleam_cors"
version = "0.2.0"

licences = ["MIT"]
description = "A CORS middleware for Gleam"
repository = { type = "github", user = "megapctr", repo = "gleam_cors" }

[dependencies]
gleam_stdlib = "~> 0.34"
gleam_http = "~> 3.5"

[dev-dependencies]
gleeunit = "~> 1.0"
