name = "gleam_cors"
version = "0.2.0"

licences = ["MIT"]
description = "A CORS middleware for Gleam"
repository = { type = "github", user = "megapctr", repo = "gleam_cors" }

[dependencies]
gleam_stdlib = "~> 0.29"
gleam_http = "~> 3.2"

[dev-dependencies]
gleeunit = "~> 0.10"
