name = "gleam_cors"
version = "0.1.0"

licences = ["MIT"]
description = "A CORS middleware for Gleam"
repository = { type = "github", user = "megapctr", repo = "gleam_cors" }

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_http = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 0.6"
