name = "gleam_cors"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# licences = ["Apache-2.0"]
description = "A CORS middleware for Gleam"
repository = { type = "github", user = "megapctr", repo = "gleam_cors" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.20"
gleam_http = "~> 3.0"

[dev-dependencies]
gleeunit = "~> 0.6"
