name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.5.0
      - uses: erlef/setup-beam@v1.15.3
        with:
          otp-version: ">25.3"
          gleam-version: ">0.28.1"
          rebar3-version: ">3.20.0"
      - run: gleam format --check src test
      - run: gleam deps download
      - run: gleam test
